

GET https://sr9r14aj77.execute-api.ap-south-1.amazonaws.com/prod/spaces
###

POST https://sr9r14aj77.execute-api.ap-south-1.amazonaws.com/prod/spaces
content-Type: application/json

{
    "location":"Paris"
}
###

GET https://sr9r14aj77.execute-api.ap-south-1.amazonaws.com/prod/spaces?id=
###

PUT https://sr9r14aj77.execute-api.ap-south-1.amazonaws.com/prod/spaces?id=1212
content-Type: application/json

{
    "location":"Paris2"
}
###